# Generated by Django 4.0.1 on 2022-01-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replies', '0004_alter_reply_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='likes',
        ),
    ]
