version: "3.9"

services:
  postgres-db:
    image: postgres:13-alpine
    volumes:
      - neotalk-data:/var/lib/postgresql/data/
    container_name: postgres-db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=neotalk_remote_user
      - POSTGRES_PASSWORD=neotalkabj4E55zm76neotalk
      - POSTGRES_DB=neotalk_db
    networks:
      - neotalk

  neotalk-back-end:
    build: ./back
    command: sh -c "(sleep 1) && (python neotalk/manage.py makemigrations) && (python neotalk/manage.py migrate) && (gunicorn --bind 0.0.0.0:8000 neotalk.wsgi --chdir neotalk/)"
    container_name: back
    networks:
      - neotalk
    depends_on:
      - postgres-db
  
  neotalk-front-end:
    build: ./front
    command: npm run build
    container_name: front
    depends_on:
      - neotalk-back-end
    volumes:
      - html-www:/front/build/
    networks:
      - neotalk

  nginx-server:
    image: nginx:1.19.8-alpine
    container_name: nginx-server
    depends_on:
      - neotalk-front-end
    ports:
      - "3002:80"
    volumes:
      - html-www:/front/build/
      - /home/trilobite/Main/Study/University/6_sem/Dockerized/neotalk/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - neotalk
    links:
      - neotalk-back-end

volumes:
  html-www:
  neotalk-data:

networks:
  neotalk:
    driver: bridge